project_name: chirpstack-geolocation-server

builds:
  - main: cmd/chirpstack-geolocation-server/main.go
    binary: chirpstack-geolocation-server
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  disable: true

nfpm:
  vendor: ChirpStack
  homepage: https://www.chirpstack.io/
  maintainer: Orne Brocaar <info@brocaar.com>
  description: ChirpStack Geolocation Server
  license: MIT
  formats:
    - deb
  bindir: /usr/bin
  files:
    "packaging/files/chirpstack-geolocation-server.rotate": "/etc/logrotate.d/chirpstack-geolocation-server"
    "packaging/files/chirpstack-geolocation-server.init": "/usr/lib/chirpstack-geolocation-server/scripts/chirpstack-geolocation-server.init"
    "packaging/files/chirpstack-geolocation-server.service": "/usr/lib/chirpstack-geolocation-server/scripts/chirpstack-geolocation-server.service"
  scripts:
    preinstall: "packaging/scripts/pre-install.sh"
    postinstall: "packaging/scripts/post-install.sh"
    postremove: "packaging/scripts/post-remove.sh"
